version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ec2-user/app
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 10
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 10
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 20
      runas: ec2-user
  ValidateService:
    - location: scripts/validate.sh
      timeout: 10
      runas: ec2-user